COPY requirements.txt .

RUN command pip install -r requirements.txt

# We use Python 3.11.11 as base
FROM python:3.11.11-slim

# Instala MLflow y otras dependencias necesarias
RUN pip install mlflow scikit-learn pandas numpy

# Usa el modelo específico del Run ID
CMD ["mlflow", "models", "serve", "-m", "runs:/0bca5ad59bec4263afb153183c87dc9c/model", "-h", "0.0.0.0", "-p", "5000"]
